# Generated by Django 4.1.7 on 2023-04-15 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_alter_team_options_team_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команда', 'verbose_name_plural': 'Команды'},
        ),
    ]
