# Generated by Django 4.1.7 on 2023-04-20 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0006_alter_startup_verify_alter_team_verify'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={},
        ),
        migrations.AddField(
            model_name='startup',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='team',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
