# Generated by Django 4.1.7 on 2023-04-24 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0007_alter_startup_options_startup_date_team_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='startup',
            options={'verbose_name': 'Стартап', 'verbose_name_plural': 'Стартапы'},
        ),
    ]
