# Generated by Django 4.1.7 on 2023-03-31 07:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Utopies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35, verbose_name='Название')),
                ('anons', models.CharField(max_length=25, verbose_name='Анонс')),
                ('slug', models.SlugField(allow_unicode=True, default=uuid.uuid4, max_length=255, verbose_name='URL')),
                ('full_text', models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(150)], verbose_name='Утопия')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Проект')),
                ('contactproject', models.URLField(default='http://', verbose_name='Ссылка на ваш проект')),
                ('author', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(related_name='Лайки', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Утопия',
                'verbose_name_plural': 'Утопии',
            },
        ),
        migrations.CreateModel(
            name='UtopiaComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('utopia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='utopies.utopies')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
