# Generated by Django 4.1.7 on 2023-03-31 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('utopies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utopies',
            name='likes',
            field=models.ManyToManyField(related_name='like', to=settings.AUTH_USER_MODEL),
        ),
    ]
