# Generated by Django 4.1.7 on 2023-04-03 14:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('utopies', '0002_alter_utopies_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utopies',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=uuid.uuid4, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
