# Generated by Django 3.2.4 on 2023-03-09 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_glavprofile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='unews_images', verbose_name='Фото')),
                ('fullest', models.TextField(max_length=90, verbose_name='Новость')),
                ('title', models.CharField(max_length=26, verbose_name='Заголовок')),
            ],
        ),
    ]
