# Generated by Django 4.1.7 on 2023-04-14 15:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.png', upload_to='profile_avatars')),
                ('bio', models.CharField(blank=True, default='Добро пожаловать на UnrealSpace! Пожалуйста, заполните свой профиль. Добавьте теги, описание, аватарку, фотографии. ', max_length=140, validators=[django.core.validators.MinLengthValidator(76)])),
                ('contact', models.URLField(default='http://')),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(allow_unicode=True, default=uuid.uuid4, max_length=255, verbose_name='URL')),
                ('raiting', models.ManyToManyField(related_name='raiting', to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
        migrations.CreateModel(
            name='AddImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images', verbose_name='Фото')),
                ('title', models.CharField(max_length=69, verbose_name='Заголовок')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Картинка пользователя',
                'verbose_name_plural': 'Картинки пользователей',
            },
        ),
    ]
