# Generated by Django 4.1.7 on 2023-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regauth', '0002_profile_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verify',
            field=models.BooleanField(default=False, verbose_name='Галочка'),
        ),
    ]
