# Generated by Django 4.1.7 on 2023-03-31 20:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itutopies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itutopies',
            name='likes',
            field=models.ManyToManyField(related_name='itlike', to=settings.AUTH_USER_MODEL),
        ),
    ]
